// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA3-SfXYbJ3VDQgs5NJUcKCh_S7hHwwXI',
    appId: '1:241486768382:web:96ebfa75550fa50573ddaf',
    messagingSenderId: '241486768382',
    projectId: 'kluksgram',
    authDomain: 'kluksgram.firebaseapp.com',
    storageBucket: 'kluksgram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAENvDmIPSZUZnZW3KN_PGh8K15RASVer0',
    appId: '1:241486768382:android:aa3b644ffd01d53273ddaf',
    messagingSenderId: '241486768382',
    projectId: 'kluksgram',
    storageBucket: 'kluksgram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrf0ELIfo03AQLef04Z0_UPCUnb6q3_CA',
    appId: '1:241486768382:ios:3ac6a1fa413c2f7973ddaf',
    messagingSenderId: '241486768382',
    projectId: 'kluksgram',
    storageBucket: 'kluksgram.appspot.com',
    iosClientId: '241486768382-d0hrntqebhb0kqolp3aj47psi30fs9ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.kluksgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrf0ELIfo03AQLef04Z0_UPCUnb6q3_CA',
    appId: '1:241486768382:ios:3ac6a1fa413c2f7973ddaf',
    messagingSenderId: '241486768382',
    projectId: 'kluksgram',
    storageBucket: 'kluksgram.appspot.com',
    iosClientId: '241486768382-d0hrntqebhb0kqolp3aj47psi30fs9ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.kluksgram',
  );
}
